name: xml
description: A lightweight XML Parser.
version: 0.9.3+1
author: John Evans <prujohn@gmail.com>
homepage: https://github.com/prujohn/dart-xml
dependencies:
  unittest: ">=0.5.5"
  browser: ">=0.4.1"
